CREATE TABLE KKU.CARD
(
    CARD_GROUP VARCHAR2(10),
    CARD_INDEX NUMBER(*),
    CARD_NO NUMBER(*),
    CARD_TITLE VARCHAR2(255),
    CARD_CONTENT VARCHAR2(255),
    PROGRESS NUMBER(*)
);
INSERT INTO KKU.CARD (CARD_GROUP, CARD_INDEX, CARD_NO, CARD_TITLE, CARD_CONTENT, PROGRESS) VALUES ('3', 4999999.5, 1, '구인수', 'springframework', 0);
INSERT INTO KKU.CARD (CARD_GROUP, CARD_INDEX, CARD_NO, CARD_TITLE, CARD_CONTENT, PROGRESS) VALUES ('4', 1249999.5, 2, '변찬우', '화상채팅', 0);
INSERT INTO KKU.CARD (CARD_GROUP, CARD_INDEX, CARD_NO, CARD_TITLE, CARD_CONTENT, PROGRESS) VALUES ('4', 624999.5, 3, '임규승', '지도API', 0);
INSERT INTO KKU.CARD (CARD_GROUP, CARD_INDEX, CARD_NO, CARD_TITLE, CARD_CONTENT, PROGRESS) VALUES ('2', 2499999.5, 4, '김지태', '캘린더API', 0);
INSERT INTO KKU.CARD (CARD_GROUP, CARD_INDEX, CARD_NO, CARD_TITLE, CARD_CONTENT, PROGRESS) VALUES ('1', 4999999.5, 5, '나진실', '로그인', 0);
INSERT INTO KKU.CARD (CARD_GROUP, CARD_INDEX, CARD_NO, CARD_TITLE, CARD_CONTENT, PROGRESS) VALUES ('3', 2499999.5, 6, '구인수', '진척도', 0);