CREATE TABLE KKU.MEMBER
(
    MEM_ID VARCHAR2(30) PRIMARY KEY NOT NULL,
    MEM_PASS VARCHAR2(255),
    MEM_NAME VARCHAR2(30)
);
INSERT INTO KKU.MEMBER (MEM_ID, MEM_PASS, MEM_NAME) VALUES ('brown', 'borown', '브라운');
INSERT INTO KKU.MEMBER (MEM_ID, MEM_PASS, MEM_NAME) VALUES ('sally', 'sally', '셀리');
INSERT INTO KKU.MEMBER (MEM_ID, MEM_PASS, MEM_NAME) VALUES ('moon', 'moon', '문');
INSERT INTO KKU.MEMBER (MEM_ID, MEM_PASS, MEM_NAME) VALUES ('bobo', 'bobo', '보보');